// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/poems': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/poems.get').default>>>>
    }
    '/api/poems/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/poems/[id].get').default>>>>
    }
    '/api/poets': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/poets.get').default>>>>
    }
    '/api/poets/:name': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/poets/[name].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}